# Bridgetown Configuration File
#
# URL is used by Bridgetown to generate canonical URLs for your site.
# For localhost/development, you don't need to set this variable.
url: "https://vicentereig.github.io" # the base hostname & protocol for your site
base_path: "/dspy.rb" # the subpath of your site for GitHub Pages
title: "DSPy.rb Documentation"
description: "Structured programming for large language models in Ruby"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Frontend bundling
frontend_bundling: esbuild

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  articles:
    output: true
    permalink: /blog/articles/:name/
    sort_by: date
    sort_direction: descending

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"

# Plugins
plugins:
  - bridgetown-builder
  - bridgetown-sitemap

# Sitemap configuration handled via config/initializers.rb

# Development settings
livereload: true
show_drafts: false

# Source configuration
source: src
destination: output

# Exclude files/folders from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .bridgetown-cache
  - gemfiles
  - package.json
  - package-lock.json
  - bun.lockb
  - esbuild.config.js
  - frontend
